### ISSUE TITLE
Project creation issue

### ISSUE THREAD

**Issue by JIghtuse** [devassistant/devassistant#376]
I tried to use devassistant on a freshly installed Fedora 22 beta. It creates a project skeleton, but then crashes with stacktrace:

    $ da create c -v -n logview
     
    INFO: Resolving RPM dependencies with DNF...
    Installing 50 RPM packages with DNF. Is this ok? [y(es)/n(o)/s(how)]: y
    Installing dependencies ...................................... Done.
    INFO: Project name will be converted to lowercase letters (logview)
    INFO: Copying c source tree to project destination
    [devassistant]$ cp -r /usr/share/devassistant/files/crt/c/. "./logview"
    DevAssistant traceback (most recent call last):
    File /usr/share/devassistant/assistants/crt/c.yaml:
      {'$clemail~': '$clemail1@$clemail1'}
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/devassistant/excepthook.py", line 49, in excepthook
        current_command_dict = frame.f_locals['command_dict']
    KeyError: 'command_dict'
     
    Original exception was:
    Traceback (most recent call last):
      File "/usr/bin/da", line 9, in <module>
        load_entry_point('devassistant==0.11.1', 'console_scripts', 'da')()
      File "/usr/lib/python3.4/site-packages/devassistant/cli/cli_runner.py", line 78, in run
        to_run.run()
      File "/usr/lib/python3.4/site-packages/devassistant/path_runner.py", line 55, in run
        self._run_path_run('', self.parsed_args)
      File "/usr/lib/python3.4/site-packages/devassistant/path_runner.py", line 33, in _run_path_run
        self.path[-1].run(stage, parsed_args)
      File "/usr/lib/python3.4/site-packages/devassistant/yaml_assistant.py", line 30, in inner
        return method(self, *args, **kwargs)
      File "/usr/lib/python3.4/site-packages/devassistant/yaml_assistant.py", line 251, in run
        return lang.run_section(getattr(self, to_run, {}), kwargs, runner=self)
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 145, in run_section
        return eval_exec_section(section, kwargs, runner)
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 167, in eval_exec_section
        retval = run_section(to_run, kwargs, runner=runner)
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 145, in run_section
        return eval_exec_section(section, kwargs, runner)
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 167, in eval_exec_section
        retval = run_section(to_run, kwargs, runner=runner)
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 145, in run_section
        return eval_exec_section(section, kwargs, runner)
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 187, in eval_exec_section
        comm_ret = eval_exec_section(comm, kwargs, runner)
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 153, in eval_exec_section
        return evaluate_expression(section, kwargs)
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 705, in evaluate_expression
        return interpr.parse(expression)
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 545, in parse
        return self.expression()
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 526, in expression
        self.token = self.next()
      File "/usr/lib/python3.4/site-packages/devassistant/lang.py", line 514, in tokenize
        raise SyntaxError("Unknown token: {tok}".format(tok=tok))
    SyntaxError: Unknown token: @

**Comment by tradej** [comment]
Hi, I'll look into this bug tomorrow.

**Comment by JIghtuse** [comment]
@tradej, actully, I already found a few issues. It is an incorrect yaml in dap-c. I'd like to fix it myself.

**Comment by tradej** [comment]
All right, feel free to submit a PR.

**Comment by tradej** [comment]
Fixed in https://github.com/JIghtuse/dap-c/commit/ee16e6688524da23ce9be0a2d1d352a0bb766412
